/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppRoomsRoomIdRouteImport } from './routes/_app.rooms.$roomId'
import { Route as AppRoomsRoomIdIndexRouteImport } from './routes/_app.rooms.$roomId.index'
import { Route as AppRoomsRoomIdChannelIdRouteImport } from './routes/_app.rooms.$roomId.$channelId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoomsRoomIdRoute = AppRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoomIdIndexRoute = AppRoomsRoomIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoomsRoomIdRoute,
} as any)
const AppRoomsRoomIdChannelIdRoute = AppRoomsRoomIdChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => AppRoomsRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/rooms/$roomId': typeof AppRoomsRoomIdRouteWithChildren
  '/rooms/$roomId/$channelId': typeof AppRoomsRoomIdChannelIdRoute
  '/rooms/$roomId/': typeof AppRoomsRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AppIndexRoute
  '/rooms/$roomId/$channelId': typeof AppRoomsRoomIdChannelIdRoute
  '/rooms/$roomId': typeof AppRoomsRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/rooms/$roomId': typeof AppRoomsRoomIdRouteWithChildren
  '/_app/rooms/$roomId/$channelId': typeof AppRoomsRoomIdChannelIdRoute
  '/_app/rooms/$roomId/': typeof AppRoomsRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/invite/$token'
    | '/rooms/$roomId'
    | '/rooms/$roomId/$channelId'
    | '/rooms/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/invite/$token'
    | '/'
    | '/rooms/$roomId/$channelId'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/invite/$token'
    | '/_app/'
    | '/_app/rooms/$roomId'
    | '/_app/rooms/$roomId/$channelId'
    | '/_app/rooms/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rooms/$roomId': {
      id: '/_app/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AppRoomsRoomIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms/$roomId/': {
      id: '/_app/rooms/$roomId/'
      path: '/'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof AppRoomsRoomIdIndexRouteImport
      parentRoute: typeof AppRoomsRoomIdRoute
    }
    '/_app/rooms/$roomId/$channelId': {
      id: '/_app/rooms/$roomId/$channelId'
      path: '/$channelId'
      fullPath: '/rooms/$roomId/$channelId'
      preLoaderRoute: typeof AppRoomsRoomIdChannelIdRouteImport
      parentRoute: typeof AppRoomsRoomIdRoute
    }
  }
}

interface AppRoomsRoomIdRouteChildren {
  AppRoomsRoomIdChannelIdRoute: typeof AppRoomsRoomIdChannelIdRoute
  AppRoomsRoomIdIndexRoute: typeof AppRoomsRoomIdIndexRoute
}

const AppRoomsRoomIdRouteChildren: AppRoomsRoomIdRouteChildren = {
  AppRoomsRoomIdChannelIdRoute: AppRoomsRoomIdChannelIdRoute,
  AppRoomsRoomIdIndexRoute: AppRoomsRoomIdIndexRoute,
}

const AppRoomsRoomIdRouteWithChildren = AppRoomsRoomIdRoute._addFileChildren(
  AppRoomsRoomIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppRoomsRoomIdRoute: typeof AppRoomsRoomIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppRoomsRoomIdRoute: AppRoomsRoomIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
